### ISSUE TITLE
UnboundLocalError: local variable 'sampled_conv_messages' referenced before assignment

### ISSUE THREAD

**Issue by maschinenzeitmaschine** [sahbic/profile-gpt#3]
Traceback (most recent call last):
  File "/Users/me/profile_gpt/venv_py3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/me/profile_gpt/profile-gpt/dashboard.py", line 59, in <module>
    processed_messages = functions.preprocess_messages(user_messages, total_desired_number_of_messages, number_of_words_max_per_message)
  File "/Users/me/profile_gpt/profile-gpt/utils/functions.py", line 83, in preprocess_messages
    sampled_messages.append(sampled_conv_messages)
UnboundLocalError: local variable 'sampled_conv_messages' referenced before assignment

**Comment by Ben-Taarit** [comment]
Duplicate of this [issue](https://github.com/sahbic/profile-gpt/issues/1)
please close

**Comment by maschinenzeitmaschine** [comment]
sorry... flakey internet
